{
 "title": "Dinas Pertanian",
 "time": { "from": "2021-01-01T11:16:48.000Z", "to": "2022-12-30T11:16:48.000Z" },
 "templating": {
  "list": [
   {
    "name": "total_organic_area",
    "label": "Total Sawah Organik",
    "query": "select sum(organic_area) as total from agricultures"
   },
   {
    "name": "total_conversion_area",
    "label": "Total Sawah Organik",
    "query": "select sum(conversion_area) as total from agricultures"
   },
   {
    "name": "total_organic",
    "label": "Total Sawah Organik",
    "query": "select sum(organic) as total from agricultures"
   },
   {
    "name": "total_conversion",
    "label": "Total Sawah Organik",
    "query": "select sum(conversion) as total from agricultures"
   },
   {
    "name": "total_grain",
    "label": "Total Gabah",
    "query": "select sum(total_grain) as total from agricultures"
   },
   {
    "name": "total_panen",
    "label": "Total Panen",
    "query": "select SUM(conversion+organic) from agricultures"
   },
   {
    "name": "total_sawah",
    "label": "Total Panen",
    "query": "select SUM(conversion_area+organic_area) from agricultures"
   },
   {
    "name": "total_lumbung",
    "label": "Total Lumbung",
    "query": "select count(*) from agricultures"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<span style=\"margin-right: 20px; margin-top:5px\">\n    <img src=\"/public/img/dispen.png\" width=\"700\" height=\"150\"/>\n  </span>"
   }
  },
  {
   "type": "geomap",
   "description": "Lokasi geografis lumbung pangan",
   "gridPos": { "h": 15, "w": 14, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "u735046609_dispertanngawi",
     "rawSql": "SELECT sum(conversion_area),lat,lg FROM u735046609_dispertanngawi.agricultures WHERE district =\"Gerih\""
    },
    {
     "dataset": "db_kspmitraartha",
     "rawSql": "SELECT sum(conversion_area),lat,lg FROM u735046609_dispertanngawi.agricultures WHERE district =\"Widodaren\""
    },
    {
     "dataset": "db_kspmitraartha",
     "rawSql": "SELECT sum(conversion_area),lat,lg FROM u735046609_dispertanngawi.agricultures WHERE district = \"Kedunggalar\""
    },
    {
     "dataset": "u735046609_dispertanngawi",
     "rawSql": "SELECT sum(conversion_area),lat,lg FROM u735046609_dispertanngawi.agricultures WHERE district = \"geneng\""
    },
    {
     "dataset": "u735046609_dispertanngawi",
     "rawSql": "SELECT sum(conversion_area),lat,lg FROM u735046609_dispertanngawi.agricultures WHERE district = \"ngrambe\""
    },
    {
     "dataset": "db_kspmitraartha",
     "rawSql": "SELECT sum(conversion_area),lat,lg FROM u735046609_dispertanngawi.agricultures WHERE district =\"Jogorogo\""
    },
    {
     "dataset": "db_kspmitraartha",
     "rawSql": "SELECT sum(conversion_area),lat,lg FROM u735046609_dispertanngawi.agricultures WHERE district =\"Mantingan\" "
    }
   ]
  },
  {
   "title": "TOTAL LUMBUNG",
   "type": "nikosc-percenttrend-panel",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 5 },
   "targets": [
    {
     "dataset": "u735046609_dispertanngawi",
     "rawSql": "SELECT count(district), count(district)-count(district)/count(district)*100 FROM u735046609_dispertanngawi.agricultures WHERE YEAR(created_at)>=\"2023\" "
    }
   ]
  },
  {
   "title": "TOTAL GABAH",
   "type": "nikosc-percenttrend-panel",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
   "targets": [
    {
     "dataset": "u735046609_dispertanngawi",
     "rawSql": "SELECT sum(total_grain), (sum(total_grain)-count(total_grain))*100/count(total_grain) FROM u735046609_dispertanngawi.agricultures WHERE YEAR(created_at)>=\"2023\""
    }
   ]
  },
  {
   "title": "TOTAL SAWAH ",
   "type": "nikosc-percenttrend-panel",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 10 },
   "targets": [
    {
     "dataset": "u735046609_dispertanngawi",
     "rawSql": "SELECT SUM(organic), (sum(organic)-count(organic))/count(organic)*100 FROM u735046609_dispertanngawi.agricultures WHERE YEAR(created_at)>=\"2023\""
    }
   ]
  },
  {
   "title": "TOTAL KONVERSI",
   "type": "nikosc-percenttrend-panel",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 10 },
   "targets": [
    {
     "dataset": "u735046609_dispertanngawi",
     "rawSql": "SELECT sum(conversion), (sum(conversion)-count(conversion))/count(conversion)*100 FROM u735046609_dispertanngawi.agricultures WHERE YEAR(created_at)>=\"2023\""
    }
   ]
  },
  {
   "title": "TOTAL PANEN",
   "type": "nikosc-percenttrend-panel",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 15 },
   "targets": [
    {
     "dataset": "u735046609_dispertanngawi",
     "rawSql": "SELECT sum(organic), (sum(organic)-count(organic))/count(organic)*100 FROM u735046609_dispertanngawi.agricultures WHERE YEAR(created_at)>=\"2023\""
    }
   ]
  },
  {
   "title": "TOTAL SAWAH ORGANIK",
   "type": "nikosc-percenttrend-panel",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 15 },
   "targets": [
    {
     "dataset": "u735046609_dispertanngawi",
     "rawSql": "SELECT sum(organic_area), (sum(organic_area)-count(organic_area))/count(organic_area)*100 FROM u735046609_dispertanngawi.agricultures WHERE YEAR(created_at)>=\"2023\" "
    }
   ]
  },
  {
   "title": "Grafik Perkembangan Panen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "db_kspmitraartha",
     "rawSql": "SELECT sum(conversion_area) as \"Perkembangan Panen\", input_at FROM u735046609_dispertanngawi.agricultures GROUP BY input_at"
    }
   ]
  },
  {
   "title": "Grafik Organic VS Konversi",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "db_kspmitraartha",
     "rawSql": "SELECT sum(organic) as \"organic\", input_at FROM u735046609_dispertanngawi.agricultures GROUP BY created_at"
    },
    {
     "dataset": "db_kspmitraartha",
     "rawSql": "SELECT sum(conversion) as \"Konversi\", input_at FROM u735046609_dispertanngawi.agricultures GROUP BY input_at"
    }
   ]
  },
  {
   "title": "BRINGIN",
   "type": "nikosc-percenttrend-panel",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 28 },
   "targets": [
    {
     "dataset": "u735046609_dispertanngawi",
     "rawSql": "SELECT COUNT(district), count(district)-count(district)/count(district)*100 FROM u735046609_dispertanngawi.agricultures WHERE district = 'bringin'AND YEAR(created_at)<=\"2023\""
    }
   ]
  },
  {
   "title": "GENENG",
   "type": "nikosc-percenttrend-panel",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 28 },
   "targets": [
    {
     "dataset": "u735046609_dispertanngawi",
     "rawSql": "SELECT COUNT(district), count(district)-COUNT(district)/count(district) FROM u735046609_dispertanngawi.agricultures WHERE district = 'geneng' AND YEAR(created_at)>=\"2023\""
    }
   ]
  },
  {
   "title": "GERIH",
   "type": "nikosc-percenttrend-panel",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 28 },
   "targets": [
    {
     "dataset": "u735046609_dispertanngawi",
     "rawSql": "SELECT COUNT(district), COUNT(district)-COUNT(district)/COUNT(district)*100 FROM u735046609_dispertanngawi.agricultures WHERE district = 'gerih' AND YEAR(created_at)>=\"2023\""
    }
   ]
  },
  {
   "title": "JOGOROGO",
   "type": "nikosc-percenttrend-panel",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 28 },
   "targets": [
    {
     "dataset": "u735046609_dispertanngawi",
     "rawSql": "SELECT COUNT(district), count(district)-count(district)/count(district)*100 FROM u735046609_dispertanngawi.agricultures WHERE district = 'jogorogo' AND YEAR(created_at)<=\"2023\""
    }
   ]
  },
  {
   "title": "MANTINGAN",
   "type": "nikosc-percenttrend-panel",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 28 },
   "targets": [
    {
     "dataset": "u735046609_dispertanngawi",
     "rawSql": "SELECT COUNT(district), COUNT(district)-COUNT(district)/COUNT(district) FROM u735046609_dispertanngawi.agricultures WHERE district = 'mantingan' "
    }
   ]
  },
  {
   "title": "NGAWI KOTA",
   "type": "nikosc-percenttrend-panel",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 28 },
   "targets": [
    {
     "dataset": "u735046609_dispertanngawi",
     "rawSql": "SELECT COUNT(district), count(district)-count(district)/count(district)*100 FROM u735046609_dispertanngawi.agricultures WHERE district = 'ngawi kota' AND YEAR(created_at)>=\"2023\""
    }
   ]
  },
  {
   "title": "KASREMAN",
   "type": "nikosc-percenttrend-panel",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 32 },
   "targets": [
    {
     "dataset": "u735046609_dispertanngawi",
     "rawSql": "SELECT COUNT(district), count(district)-count(district)/count(district)*100 FROM u735046609_dispertanngawi.agricultures WHERE district = 'kasreman' and YEAR(created_at)<=\"2023\""
    }
   ]
  },
  {
   "title": "KEDUNGGALAR",
   "type": "nikosc-percenttrend-panel",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 32 },
   "targets": [
    {
     "dataset": "u735046609_dispertanngawi",
     "rawSql": "SELECT COUNT(district), count(district)-count(district)/count(district)*100 FROM u735046609_dispertanngawi.agricultures WHERE district = 'kedunggalar' AND YEAR(created_at)<=\"2023\""
    }
   ]
  },
  {
   "title": "KENDAL",
   "type": "nikosc-percenttrend-panel",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 32 },
   "targets": [
    {
     "dataset": "u735046609_dispertanngawi",
     "rawSql": "SELECT COUNT(district), count(district)-count(district)/count(district)*100 FROM u735046609_dispertanngawi.agricultures WHERE district = 'kendal' AND YEAR(created_at)<=\"2023\""
    }
   ]
  },
  {
   "title": "KWADUNGAN",
   "type": "nikosc-percenttrend-panel",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 32 },
   "targets": [
    {
     "dataset": "u735046609_dispertanngawi",
     "rawSql": "SELECT COUNT(district), (count(district)-count(district))/count(district)*100 FROM u735046609_dispertanngawi.agricultures WHERE district = 'Kwadungan' AND YEAR(created_at)<=\"2023\""
    }
   ]
  },
  {
   "title": "KARANGANYAR",
   "type": "nikosc-percenttrend-panel",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 32 },
   "targets": [
    {
     "dataset": "u735046609_dispertanngawi",
     "rawSql": "SELECT COUNT(district), (count(district)-count(district))/count(district)*100 FROM u735046609_dispertanngawi.agricultures WHERE district = 'Karanganyar' AND YEAR(created_at)<=\"2023\""
    }
   ]
  },
  {
   "title": "KARANGJATI",
   "type": "nikosc-percenttrend-panel",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 32 },
   "targets": [
    {
     "dataset": "u735046609_dispertanngawi",
     "rawSql": "SELECT COUNT(district), (count(district)-count(district))/count(district)*100 FROM u735046609_dispertanngawi.agricultures WHERE district = 'karangjati' AND YEAR(created_at)<=\"2023\""
    }
   ]
  },
  {
   "type": "nikosc-percenttrend-panel",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 36 },
   "targets": [
    {
     "dataset": "u735046609_dispertanngawi",
     "rawSql": "SELECT COUNT(district), (count(district)-count(district))/count(district)*100 FROM u735046609_dispertanngawi.agricultures WHERE district = 'ngrambe' AND YEAR(created_at)<=\"2023\""
    }
   ]
  },
  {
   "title": "PADAS",
   "type": "nikosc-percenttrend-panel",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 36 },
   "targets": [
    {
     "dataset": "u735046609_dispertanngawi",
     "rawSql": "SELECT COUNT(district), count(district)-count(district)/count(district)*100 FROM u735046609_dispertanngawi.agricultures WHERE district = 'padas' AND YEAR(created_at)<=\"2023\""
    }
   ]
  },
  {
   "title": "PANGKUR",
   "type": "nikosc-percenttrend-panel",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 36 },
   "targets": [
    {
     "dataset": "u735046609_dispertanngawi",
     "rawSql": "SELECT COUNT(district), count(district)-count(district)/count(district)*100 FROM u735046609_dispertanngawi.agricultures WHERE district = 'pangkur' AND YEAR(created_at)<=\"2023\""
    }
   ]
  },
  {
   "title": "PITU",
   "type": "nikosc-percenttrend-panel",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 36 },
   "targets": [
    {
     "dataset": "u735046609_dispertanngawi",
     "rawSql": "SELECT COUNT(district), count(district)-count(district)/count(district)*100 FROM u735046609_dispertanngawi.agricultures WHERE district = 'pitu' AND YEAR(created_at)<=\"2023\""
    }
   ]
  },
  {
   "title": "SINE",
   "type": "nikosc-percenttrend-panel",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 36 },
   "targets": [
    {
     "dataset": "u735046609_dispertanngawi",
     "rawSql": "SELECT COUNT(district), count(district)-count(district)/count(district)*100 FROM u735046609_dispertanngawi.agricultures WHERE district = 'sine' AND YEAR(created_at)<=\"2023\""
    }
   ]
  },
  {
   "title": "WIDODAREN",
   "type": "nikosc-percenttrend-panel",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 36 },
   "targets": [
    {
     "dataset": "u735046609_dispertanngawi",
     "rawSql": "SELECT COUNT(district), count(district)-count(district)/count(district)*100 FROM u735046609_dispertanngawi.agricultures WHERE district = 'widodaren' AND YEAR(created_at)<=\"2023\""
    }
   ]
  },
  {
   "title": "PARON",
   "type": "nikosc-percenttrend-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "dataset": "u735046609_dispertanngawi",
     "rawSql": "SELECT COUNT(district), count(district)-count(district)/count(district)*100 FROM u735046609_dispertanngawi.agricultures WHERE district = 'paron' AND YEAR(created_at)<=\"2023\""
    }
   ]
  }
 ]
}