version: "3.6"

networks:
  grafnet:
    external: false

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    networks:
      - grafnet
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mariadb/data:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    networks:
      - grafnet
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: root
      PMA_ABSOLUTE_URI: https://dashboard.ngawikab.go.id/phpmyadmin
    ports:
      - 8081:80
    restart: unless-stopped
    depends_on:
      - mariadb
  nginx:
    image: nginx:alpine
    container_name: nginx-www
    restart: unless-stopped
    tty: true
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./cert:/etc/cert
    networks:
      - grafnet
    ports:
      - 80:80
      - 443:443
  # My grafana service
  grafana:
    image: grafana/grafana
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - grafnet

# Explicitly define the persistent volume for your data storage
volumes:
  grafana-data:
    name: grafana-data
    external: false
