version: "3.6"

networks:
  grafnet:
    external: false

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-www
    restart: unless-stopped
    tty: true
    volumes: 
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
    networks:
      - grafnet
    ports:
      - 80:80
      - 443:443
  # My grafana service
  grafana:
    image: grafana/grafana
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - grafnet
# Explicitly define the persistent volume for your data storage
volumes:
  grafana-data:
    name: grafana-data
    external: false
